### ISSUE TITLE
Wisełka Kraków - jebać żydów

### ISSUE THREAD

**Issue by VeQ0** [Shieldowskyy/DashoBot#2]
Ide z ziomalem, na kazimierzowskie
zza bloku wyskoczyły KURWY Żydowskie
a tam chlopaki przypadkowo stali
i widzac to wszystko Żydom dojebali
Żyd to frajer, żyd to buc żyje poto by go tłuc
Żyd to frajer, żyd to buc żyje poto by go tłuc
I ja na koniec wam zarymuje
Pierdolcie sie wszystkie żydowskie chuje
Żyd to frajer, żyd to buc żyje poto by go tłuc
W imieniu moim i bliskich JEBAC ŻYDOW WSZYSTKICH

**Comment by Shieldowskyy** [comment]
tak
